<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\Logging\" />
    <Folder Include="Services\Inventory\" />
    <Folder Include="Services\Logging\" />
    <Folder Include="Services\Payments\" />
    <Folder Include="Services\Orders\" />
    <Folder Include="Services\Products\" />
  </ItemGroup>

</Project>
